// Auto-generated fallback copy of data/hospitals.json. Keep in sync when data updates.
export const EMBEDDED_HOSPITALS = [
  {
    "name": "Avondale Pharmacy",
    "province": "Harare",
    "city": "Harare",
    "address": "Avondale Shopping Centre, King George Rd, Harare",
    "type": "private",
    "ownership": "independent",
    "bed_count": null,
    "specialists": [
      "pharmacy",
      "over-the-counter"
    ],
    "tier": "T3",
    "phone": "+263 24 230 4455",
    "website": "",
    "latitude": -17.789,
    "longitude": 31.034,
    "category": "pharmacy",
    "operating_hours": "Mon-Sat 08:00-21:00; Sun 09:00-18:00",
    "manager": "Pharmacy manager: L. Chikandiwa",
    "last_verified": "2025-11-20",
    "id": "avondale-pharmacy-harare"
  },
  {
    "name": "Baines Imaging Group",
    "province": "Harare",
    "city": "Harare",
    "address": "88 Baines Ave, Harare",
    "type": "private",
    "ownership": "corporate",
    "bed_count": null,
    "specialists": [
      "radiology",
      "imaging"
    ],
    "tier": "T3",
    "phone": "+263-24-274-8471",
    "website": "https://www.bainesimaginggroup.com",
    "latitude": -17.8267,
    "longitude": 31.0526,
    "id": "baines-imaging-group-harare",
    "last_verified": "2025-11-20",
    "category": "imaging_centre",
    "operating_hours": "Mon-Fri 07:30-17:00; Sat 08:00-12:00",
    "manager": "Operations manager: TBD"
  },
  {
    "name": "Borrowdale Trauma Centre",
    "province": "Harare",
    "city": "Harare",
    "address": "Borrowdale Rd, Harare",
    "type": "private",
    "ownership": "corporate",
    "bed_count": 80,
    "specialists": [
      "trauma",
      "icu"
    ],
    "tier": "T3",
    "phone": "+263-4-870-000",
    "website": "https://www.traumacentre.co.zw",
    "latitude": -17.7645,
    "longitude": 31.0987,
    "id": "borrowdale-trauma-centre-harare",
    "last_verified": "2025-11-20",
    "category": "hospital",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Operations manager: TBD"
  },
  {
    "id": "chinoyi-provincial-hospital",
    "name": "Chinhoyi Provincial Hospital",
    "province": "Mashonaland West",
    "city": "Chinhoyi",
    "address": "Hospital Road, Chinhoyi",
    "type": "public",
    "ownership": "government",
    "bed_count": 120,
    "specialists": [
      "general",
      "maternity"
    ],
    "tier": "T2",
    "phone": "+263-67-212-3456",
    "website": "",
    "latitude": -17.3669,
    "longitude": 30.2007,
    "last_verified": "2025-11-20",
    "category": "hospital",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Operations manager: TBD"
  },
  {
    "name": "City Dental Clinic",
    "province": "Harare",
    "city": "Harare",
    "address": "58 Jason Moyo Ave, Harare",
    "type": "private",
    "ownership": "independent",
    "bed_count": null,
    "specialists": [
      "dentistry",
      "oral_surgery"
    ],
    "tier": "T3",
    "phone": "+263 24 252 1199",
    "website": "",
    "latitude": -17.8293,
    "longitude": 31.0535,
    "category": "dental_clinic",
    "operating_hours": "Mon-Fri 08:00-17:30; Sat 08:00-13:00",
    "manager": "Clinic manager: Dr. T. Moyo",
    "last_verified": "2025-11-20",
    "id": "city-dental-clinic-harare"
  },
  {
    "name": "Gweru Provincial Hospital",
    "province": "Midlands",
    "city": "Gweru",
    "address": "Hospital Rd, Gweru",
    "type": "public",
    "ownership": "government",
    "bed_count": 320,
    "specialists": [
      "general",
      "maternity"
    ],
    "tier": "T1",
    "phone": "+263-54-222-333",
    "website": "",
    "latitude": -19.454,
    "longitude": 29.819,
    "id": "gweru-provincial-hospital-gweru",
    "last_verified": "2025-11-20",
    "category": "hospital",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Operations manager: TBD"
  },
  {
    "id": "harare-central-hospital",
    "name": "Harare Central Hospital",
    "province": "Harare",
    "city": "Harare",
    "address": "42Q7+P55, Talbot Rd, Harare, Zimbabwe",
    "type": "public",
    "ownership": "government",
    "bed_count": 1000,
    "specialists": [
      "cardiology",
      "oncology",
      "pediatrics"
    ],
    "tier": "T1",
    "phone": "+263 24 2621100 ext. 19",
    "website": "https://health.gov.zw/harare-hospital",
    "latitude": -17.8298,
    "longitude": 31.053,
    "last_verified": "2025-11-20",
    "category": "hospital",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Operations manager: TBD"
  },
  {
    "id": "karanda-mission-hospital",
    "name": "Karanda Mission Hospital",
    "province": "Mashonaland Central",
    "city": "Mount Darwin",
    "address": "Karanda Road, Mount Darwin",
    "type": "mission",
    "ownership": "church",
    "bed_count": 150,
    "specialists": [
      "surgery",
      "maternity",
      "general"
    ],
    "tier": "T2",
    "phone": "+263-271-2020",
    "website": "https://www.karanda.org",
    "latitude": -16.7586,
    "longitude": 31.5686,
    "last_verified": "2024-04-01",
    "category": "hospital",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Operations manager: TBD"
  },
  {
    "name": "Makumbe Mission Hospital",
    "province": "Manicaland",
    "city": "Buhera",
    "address": "Buhera Growth Point",
    "type": "mission",
    "ownership": "church",
    "bed_count": 150,
    "specialists": [
      "general",
      "maternity"
    ],
    "tier": "T2",
    "phone": "",
    "website": "",
    "latitude": -19.325,
    "longitude": 31.427,
    "id": "makumbe-mission-hospital-buhera",
    "last_verified": "2025-11-20",
    "category": "hospital",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Operations manager: TBD"
  },
  {
    "name": "Makumbi Mission Hospital",
    "province": "Mashonaland Central",
    "city": "Domboshava",
    "address": "Domboshava Rd",
    "type": "mission",
    "ownership": "church",
    "bed_count": 90,
    "specialists": [
      "general",
      "outpatient"
    ],
    "tier": "T3",
    "phone": "",
    "website": "",
    "latitude": -17.603,
    "longitude": 31.17,
    "id": "makumbi-mission-hospital-domboshava",
    "last_verified": "2025-11-20",
    "category": "hospital",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Operations manager: TBD"
  },
  {
    "id": "mater-dei-hospital",
    "name": "Mater Dei Hospital",
    "province": "Bulawayo",
    "city": "Bulawayo",
    "address": "43 Lobengula Street, Bulawayo",
    "type": "private",
    "ownership": "church",
    "bed_count": 200,
    "specialists": [
      "maternity",
      "orthopedics"
    ],
    "tier": "T2",
    "phone": "+263-9-202-940",
    "website": "https://www.materdei.co.zw",
    "latitude": -20.1604,
    "longitude": 28.5887,
    "last_verified": "2024-04-01",
    "category": "hospital",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Operations manager: TBD"
  },
  {
    "name": "Mazowe District Hospital",
    "province": "Mashonaland Central",
    "city": "Mazowe",
    "address": "Mazowe Town",
    "type": "public",
    "ownership": "government",
    "bed_count": 110,
    "specialists": [
      "general"
    ],
    "tier": "T2",
    "phone": "",
    "website": "",
    "latitude": -17.476,
    "longitude": 30.98,
    "id": "mazowe-district-hospital-mazowe",
    "last_verified": "2025-11-20",
    "category": "hospital",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Operations manager: TBD"
  },
  {
    "id": "mutare-provincial-hospital",
    "name": "Mutare Provincial Hospital",
    "province": "Manicaland",
    "city": "Mutare",
    "address": "Hospital Road, Mutare",
    "type": "public",
    "ownership": "government",
    "bed_count": 250,
    "specialists": [
      "general",
      "maternity"
    ],
    "tier": "T2",
    "phone": "+263-20-60800",
    "website": "https://health.gov.zw/mutare-hospital",
    "latitude": -18.965,
    "longitude": 32.674,
    "last_verified": "2024-04-01",
    "category": "hospital",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Operations manager: TBD"
  },
  {
    "name": "Opticare Opticians Bulawayo",
    "province": "Bulawayo",
    "city": "Bulawayo",
    "address": "93 Fife Street, Bulawayo",
    "type": "private",
    "ownership": "independent",
    "bed_count": null,
    "specialists": [
      "optometry",
      "eyewear"
    ],
    "tier": "T3",
    "phone": "+263 29 226 2213",
    "website": "",
    "latitude": -20.158,
    "longitude": 28.588,
    "category": "optician",
    "operating_hours": "Mon-Sat 08:00-17:00",
    "manager": "Store manager: S. Ndlovu",
    "last_verified": "2025-11-20",
    "id": "opticare-opticians-bulawayo-bulawayo"
  },
  {
    "id": "parirenyatwa-group-hospitals",
    "name": "Parirenyatwa Group of Hospitals",
    "province": "Harare",
    "city": "Harare",
    "address": "Mazowe Street, Harare",
    "type": "public",
    "ownership": "government",
    "bed_count": 1800,
    "specialists": [
      "cardiology",
      "surgery",
      "obstetrics",
      "oncology"
    ],
    "tier": "T1",
    "phone": "+263-4-703-000",
    "website": "https://www.parihosp.org.zw",
    "latitude": -17.815,
    "longitude": 31.0534,
    "last_verified": "2024-04-01",
    "category": "hospital",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Operations manager: TBD"
  },
  {
    "name": "The Avenues Clinic",
    "province": "Harare",
    "city": "Harare",
    "address": "7 Josiah Chinamano Ave, Harare",
    "type": "private",
    "ownership": "corporate",
    "bed_count": 176,
    "specialists": [
      "general",
      "maternity",
      "icu",
      "oncology"
    ],
    "tier": "T2",
    "phone": "+263-4-707-861",
    "website": "https://www.avenuesclinic.co.zw",
    "latitude": -17.8213,
    "longitude": 31.0445,
    "id": "the-avenues-clinic-harare",
    "last_verified": "2025-11-20",
    "category": "hospital",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Operations manager: TBD"
  },
  {
    "name": "Westend Clinic",
    "province": "Harare",
    "city": "Harare",
    "address": "71 Baines Ave, Harare",
    "type": "private",
    "ownership": "corporate",
    "bed_count": 40,
    "specialists": [
      "general",
      "maternity",
      "trauma"
    ],
    "tier": "T3",
    "phone": "+263 24 252 0452",
    "website": "",
    "latitude": -17.8245,
    "longitude": 31.0541,
    "category": "clinic",
    "operating_hours": "24/7 for emergencies; outpatient 08:00-17:00",
    "manager": "Clinic administrator: P. Nyathi",
    "last_verified": "2025-11-20",
    "id": "westend-clinic-harare"
  }
];
