// Auto-generated hospital dataset.
// Refresh via: npm run prepare:data
export const hospitalsData = [
  {
    "id": "ekusileni-medical-centre-bulawayo",
    "name": "Ekusileni Medical Centre",
    "aliases": [],
    "facility_type": "Hospital",
    "ownership": "Corporate",
    "rural_urban": "Urban",
    "province": "Bulawayo",
    "district": "Bulawayo",
    "ward": "",
    "city": "Bulawayo",
    "address": "",
    "services": [
      "specialist",
      "orthopedics",
      "cardiology"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "green-cross-pharmacy-bulawayo-bulawayo",
    "name": "Green Cross Pharmacy Bulawayo",
    "aliases": [
      "Green Cross Pharmacy Bulawayo"
    ],
    "facility_type": "Pharmacy",
    "ownership": "Private",
    "rural_urban": "Urban",
    "province": "Bulawayo",
    "district": "Bulawayo",
    "ward": "",
    "city": "Bulawayo",
    "address": "",
    "services": [
      "Dispensary"
    ],
    "open_24h": true,
    "emergency_level": "Basic",
    "cost_band": null,
    "medical_aids": [],
    "phone": "+263 29 227 111",
    "whatsapp": "+263 29 227 111",
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [
      "mcaz_pharmacies_2024"
    ],
    "confidence": "high",
    "verified": true,
    "website": "",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "mater-dei-hospital",
    "name": "Mater Dei Hospital",
    "aliases": [
      "Mater Dei Hospital"
    ],
    "facility_type": "Hospital",
    "ownership": "Church",
    "rural_urban": "Urban",
    "province": "Bulawayo",
    "district": "Bulawayo",
    "ward": "",
    "city": "Bulawayo",
    "address": "43 Lobengula Street, Bulawayo",
    "services": [
      "maternity",
      "orthopedics"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "cash",
      "international medical aid",
      "local medical aid",
      "mobile money"
    ],
    "phone": "+263-9-202-940",
    "whatsapp": "+263-9-202-940",
    "email": null,
    "lat": -20.1604,
    "lon": 28.5887,
    "tier": "Tier 2",
    "last_verified": "2024-04-01",
    "source": [
      "hpa_registry"
    ],
    "confidence": "high",
    "verified": false,
    "website": "https://www.materdei.co.zw",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "mpilo-central-hospital-bulawayo",
    "name": "Mpilo Central Hospital",
    "aliases": [],
    "facility_type": "Central Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Bulawayo",
    "district": "Bulawayo",
    "ward": "",
    "city": "Bulawayo",
    "address": "",
    "services": [
      "general",
      "maternity",
      "surgery",
      "teaching"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 1",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "opticare-opticians-bulawayo-bulawayo",
    "name": "Opticare Opticians Bulawayo",
    "aliases": [],
    "facility_type": "Optician",
    "ownership": "Independent",
    "rural_urban": "Urban",
    "province": "Bulawayo",
    "district": "Bulawayo",
    "ward": "",
    "city": "Bulawayo",
    "address": "93 Fife Street, Bulawayo",
    "services": [
      "optometry",
      "eyewear"
    ],
    "open_24h": false,
    "emergency_level": "Basic",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": "+263 29 226 2213",
    "whatsapp": "+263 29 226 2213",
    "email": null,
    "lat": -20.158,
    "lon": 28.588,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "united-bulawayo-hospitals-bulawayo",
    "name": "United Bulawayo Hospitals",
    "aliases": [],
    "facility_type": "Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Bulawayo",
    "district": "Bulawayo",
    "ward": "",
    "city": "Bulawayo",
    "address": "",
    "services": [
      "general",
      "maternity",
      "surgery",
      "teaching"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 1",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "chitungwiza-central-hospital-chitungwiza",
    "name": "Chitungwiza Central Hospital",
    "aliases": [],
    "facility_type": "Central Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Chitungwiza",
    "ward": "",
    "city": "Chitungwiza",
    "address": "",
    "services": [
      "general",
      "maternity",
      "surgery",
      "teaching"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 1",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "avondale-pharmacy-harare",
    "name": "Avondale Pharmacy",
    "aliases": [],
    "facility_type": "Pharmacy",
    "ownership": "Independent",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "Avondale Shopping Centre, King George Rd, Harare",
    "services": [
      "pharmacy",
      "over-the-counter"
    ],
    "open_24h": false,
    "emergency_level": "Basic",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": "+263 24 230 4455",
    "whatsapp": "+263 24 230 4455",
    "email": null,
    "lat": -17.789,
    "lon": 31.034,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "baines-imaging-group-harare",
    "name": "Baines Imaging Group",
    "aliases": [],
    "facility_type": "Health Facility",
    "ownership": "Corporate",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "88 Baines Ave, Harare",
    "services": [
      "radiology",
      "imaging"
    ],
    "open_24h": false,
    "emergency_level": "Basic",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": "+263-24-274-8471",
    "whatsapp": "+263-24-274-8471",
    "email": null,
    "lat": -17.8267,
    "lon": 31.0526,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": "https://www.bainesimaginggroup.com"
  },
  {
    "id": "beatrice-road-infectious-diseases-hospital-harare",
    "name": "Beatrice Road Infectious Diseases Hospital",
    "aliases": [],
    "facility_type": "Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "Simon Mazorodze Rd, Mbare, Harare",
    "services": [
      "infectious_diseases"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": "+263 4 775 824 / +263 4 752 726 / +263 4 792 761",
    "whatsapp": "+263 4 775 824 / +263 4 752 726 / +263 4 792 761",
    "email": null,
    "lat": -17.861,
    "lon": 31.026,
    "tier": "Tier 1",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "borrowdale-trauma-centre-harare",
    "name": "Borrowdale Trauma Centre",
    "aliases": [
      "Borrowdale Trauma Centre"
    ],
    "facility_type": "Private Hospital",
    "ownership": "Corporate",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "Borrowdale Rd, Harare",
    "services": [
      "ICU",
      "Trauma"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "cash",
      "international medical aid",
      "local medical aid",
      "mobile money"
    ],
    "phone": "+263-4-870-000",
    "whatsapp": "+263-4-870-000",
    "email": null,
    "lat": -17.7645,
    "lon": 31.0987,
    "tier": "Tier 1",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "high",
    "verified": false,
    "website": "https://www.traumacentre.co.zw",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "city-dental-clinic-harare",
    "name": "City Dental Clinic",
    "aliases": [],
    "facility_type": "Clinic",
    "ownership": "Independent",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "58 Jason Moyo Ave, Harare",
    "services": [
      "dentistry",
      "oral_surgery",
      "orthodontist",
      "orthodontics",
      "dental surgery"
    ],
    "open_24h": false,
    "emergency_level": "Basic",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": "+263 24 252 1199",
    "whatsapp": "+263 24 252 1199",
    "email": null,
    "lat": -17.8293,
    "lon": 31.0535,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "harare-central-hospital",
    "name": "Harare Central Hospital",
    "aliases": [],
    "facility_type": "Central Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "42Q7+P55, Talbot Rd, Harare, Zimbabwe",
    "services": [
      "cardiology",
      "oncology",
      "pediatrics"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": "+263 24 2621100 ext. 19",
    "whatsapp": "+263 24 2621100 ext. 19",
    "email": null,
    "lat": -17.8298,
    "lon": 31.053,
    "tier": "Tier 1",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": "https://health.gov.zw/harare-hospital"
  },
  {
    "id": "parirenyatwa-group-hospitals",
    "name": "Parirenyatwa Group of Hospitals",
    "aliases": [],
    "facility_type": "Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "Mazowe Street, Harare",
    "services": [
      "cardiology",
      "surgery",
      "obstetrics",
      "oncology"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": "+263-4-703-000",
    "whatsapp": "+263-4-703-000",
    "email": null,
    "lat": -17.815,
    "lon": 31.0534,
    "tier": "Tier 1",
    "last_verified": "2024-04-01",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": "https://www.parihosp.org.zw"
  },
  {
    "id": "premier-pharmacy-harare-harare",
    "name": "Premier Pharmacy Harare",
    "aliases": [
      "Premier Pharmacy Harare"
    ],
    "facility_type": "Pharmacy",
    "ownership": "Private",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "",
    "services": [
      "Dispensary"
    ],
    "open_24h": false,
    "emergency_level": "Basic",
    "cost_band": null,
    "medical_aids": [],
    "phone": "+263 24 275 1234",
    "whatsapp": "+263 24 275 1234",
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [
      "mcaz_pharmacies_2024"
    ],
    "confidence": "high",
    "verified": true,
    "website": "",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "st-annes-hospital-harare",
    "name": "St Anne's Hospital",
    "aliases": [],
    "facility_type": "Hospital",
    "ownership": "Church",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "",
    "services": [
      "general",
      "maternity",
      "surgery"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "the-avenues-clinic-harare",
    "name": "The Avenues Clinic",
    "aliases": [
      "The Avenues Clinic"
    ],
    "facility_type": "Clinic",
    "ownership": "Corporate",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "7 Josiah Chinamano Ave, Harare",
    "services": [
      "general",
      "icu",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Basic",
    "cost_band": null,
    "medical_aids": [
      "cash",
      "international medical aid",
      "local medical aid",
      "mobile money"
    ],
    "phone": "+263-4-707-861",
    "whatsapp": "+263-4-707-861",
    "email": null,
    "lat": -17.8212,
    "lon": 31.0459,
    "tier": "Tier 1",
    "last_verified": "2025-11-20",
    "source": [
      "hpa_registry"
    ],
    "confidence": "high",
    "verified": false,
    "website": "https://www.avenuesclinic.co.zw",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "west-end-hospital-harare",
    "name": "West End Hospital",
    "aliases": [],
    "facility_type": "Hospital",
    "ownership": "Corporate",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "",
    "services": [
      "general",
      "surgery"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "westend-clinic-harare",
    "name": "Westend Clinic",
    "aliases": [],
    "facility_type": "Clinic",
    "ownership": "Corporate",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "71 Baines Ave, Harare",
    "services": [
      "general",
      "maternity",
      "trauma"
    ],
    "open_24h": true,
    "emergency_level": "Basic",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": "+263 24 252 0452",
    "whatsapp": "+263 24 252 0452",
    "email": null,
    "lat": -17.8245,
    "lon": 31.0541,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "wilkins-infectious-diseases-hospital-harare",
    "name": "Wilkins Infectious Diseases Hospital",
    "aliases": [],
    "facility_type": "Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "Rekai Tangwena Ave & Josiah Tongogara St, Harare",
    "services": [
      "infectious diseases",
      "isolation",
      "public health"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": -17.8296,
    "lon": 31.045,
    "tier": "Tier 1",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": "https://en.wikipedia.org/wiki/Wilkins_Infectious_Diseases_Hospital"
  },
  {
    "id": "makumbe-mission-hospital-buhera",
    "name": "Makumbe Mission Hospital",
    "aliases": [],
    "facility_type": "Mission Hospital",
    "ownership": "Church",
    "rural_urban": "Urban",
    "province": "Manicaland",
    "district": "Buhera",
    "ward": "",
    "city": "Buhera",
    "address": "Buhera Growth Point",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": -19.325,
    "lon": 31.427,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "murambinda-mission-hospital-buhera",
    "name": "Murambinda Mission Hospital",
    "aliases": [],
    "facility_type": "Mission Hospital",
    "ownership": "Church",
    "rural_urban": "Urban",
    "province": "Manicaland",
    "district": "Buhera",
    "ward": "",
    "city": "Buhera",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "chipinge-district-hospital-chipinge",
    "name": "Chipinge District Hospital",
    "aliases": [
      "Chipinge District Hospital"
    ],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Manicaland",
    "district": "Chipinge",
    "ward": "",
    "city": "Chipinge",
    "address": "",
    "services": [
      "ER",
      "Inpatient",
      "Lab",
      "Maternity"
    ],
    "open_24h": false,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [
      "scribd_provincial_district_hospitals"
    ],
    "confidence": "high",
    "verified": false,
    "website": "",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "mutare-central-pharmacy-mutare",
    "name": "Mutare Central Pharmacy",
    "aliases": [
      "Mutare Central Pharmacy"
    ],
    "facility_type": "Pharmacy",
    "ownership": "Private",
    "rural_urban": "Urban",
    "province": "Manicaland",
    "district": "Mutare",
    "ward": "",
    "city": "Mutare",
    "address": "",
    "services": [
      "Dispensary"
    ],
    "open_24h": false,
    "emergency_level": "Basic",
    "cost_band": null,
    "medical_aids": [],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [
      "mcaz_pharmacies_2024"
    ],
    "confidence": "high",
    "verified": true,
    "website": "",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "mutare-provincial-hospital",
    "name": "Mutare Provincial Hospital",
    "aliases": [],
    "facility_type": "Provincial Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Manicaland",
    "district": "Mutare",
    "ward": "",
    "city": "Mutare",
    "address": "Hospital Road, Mutare",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": "+263-20-60800",
    "whatsapp": "+263-20-60800",
    "email": null,
    "lat": -18.965,
    "lon": 32.674,
    "tier": "Tier 2",
    "last_verified": "2024-04-01",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": "https://health.gov.zw/mutare-hospital"
  },
  {
    "id": "st-josephs-mission-hospital-mutasa",
    "name": "St Joseph's Mission Hospital",
    "aliases": [],
    "facility_type": "Mission Hospital",
    "ownership": "Church",
    "rural_urban": "Urban",
    "province": "Manicaland",
    "district": "Mutasa",
    "ward": "",
    "city": "Mutasa",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "nyanga-district-hospital-nyanga",
    "name": "Nyanga District Hospital",
    "aliases": [
      "Nyanga District Hospital"
    ],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Manicaland",
    "district": "Nyanga",
    "ward": "",
    "city": "Nyanga",
    "address": "",
    "services": [
      "ER",
      "Inpatient",
      "Lab",
      "Maternity"
    ],
    "open_24h": false,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [
      "scribd_provincial_district_hospitals"
    ],
    "confidence": "high",
    "verified": false,
    "website": "",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "rusape-general-hospital-rusape",
    "name": "Rusape General Hospital",
    "aliases": [],
    "facility_type": "Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Manicaland",
    "district": "Rusape",
    "ward": "",
    "city": "Rusape",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "bindura-provincial-hospital-bindura",
    "name": "Bindura Provincial Hospital",
    "aliases": [],
    "facility_type": "Provincial Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Mashonaland Central",
    "district": "Bindura",
    "ward": "",
    "city": "Bindura",
    "address": "P85H+R7P, Bindura, Zimbabwe",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": "+263 78 016 2553",
    "whatsapp": "+263 78 016 2553",
    "email": null,
    "lat": -17.296,
    "lon": 31.33,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "concession-district-hospital-concession",
    "name": "Concession District Hospital",
    "aliases": [],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Mashonaland Central",
    "district": "Concession",
    "ward": "",
    "city": "Concession",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "makumbi-mission-hospital-domboshava",
    "name": "Makumbi Mission Hospital",
    "aliases": [],
    "facility_type": "Mission Hospital",
    "ownership": "Church",
    "rural_urban": "Urban",
    "province": "Mashonaland Central",
    "district": "Domboshava",
    "ward": "",
    "city": "Domboshava",
    "address": "Domboshava Rd",
    "services": [
      "general",
      "outpatient"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": -17.603,
    "lon": 31.17,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "mazowe-district-hospital-mazowe",
    "name": "Mazowe District Hospital",
    "aliases": [],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Mashonaland Central",
    "district": "Mazowe",
    "ward": "",
    "city": "Mazowe",
    "address": "Mazowe Town",
    "services": [
      "general"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": -17.476,
    "lon": 30.98,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "karanda-mission-hospital",
    "name": "Karanda Mission Hospital",
    "aliases": [],
    "facility_type": "Mission Hospital",
    "ownership": "Church",
    "rural_urban": "Urban",
    "province": "Mashonaland Central",
    "district": "Mount Darwin",
    "ward": "",
    "city": "Mount Darwin",
    "address": "Karanda Road, Mount Darwin",
    "services": [
      "surgery",
      "maternity",
      "general"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": "+263-271-2020",
    "whatsapp": "+263-271-2020",
    "email": null,
    "lat": -16.7586,
    "lon": 31.5686,
    "tier": "Tier 2",
    "last_verified": "2024-04-01",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": "https://www.karanda.org"
  },
  {
    "id": "mvurwi-hospital-mvurwi",
    "name": "Mvurwi Hospital",
    "aliases": [],
    "facility_type": "Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Mashonaland Central",
    "district": "Mvurwi",
    "ward": "",
    "city": "Mvurwi",
    "address": "",
    "services": [
      "general"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "marondera-provincial-hospital-marondera",
    "name": "Marondera Provincial Hospital",
    "aliases": [],
    "facility_type": "Provincial Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Mashonaland East",
    "district": "Marondera",
    "ward": "",
    "city": "Marondera",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "murewa-district-hospital-murewa",
    "name": "Murewa District Hospital",
    "aliases": [],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Mashonaland East",
    "district": "Murewa",
    "ward": "",
    "city": "Murewa",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "mutoko-district-hospital-mutoko",
    "name": "Mutoko District Hospital",
    "aliases": [],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Mashonaland East",
    "district": "Mutoko",
    "ward": "",
    "city": "Mutoko",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "chinoyi-provincial-hospital",
    "name": "Chinhoyi Provincial Hospital",
    "aliases": [],
    "facility_type": "Provincial Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Mashonaland West",
    "district": "Chinhoyi",
    "ward": "",
    "city": "Chinhoyi",
    "address": "Hospital Road, Chinhoyi",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": "+263-67-212-3456",
    "whatsapp": "+263-67-212-3456",
    "email": null,
    "lat": -17.3669,
    "lon": 30.2007,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "kadoma-general-hospital-kadoma",
    "name": "Kadoma General Hospital",
    "aliases": [],
    "facility_type": "Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Mashonaland West",
    "district": "Kadoma",
    "ward": "",
    "city": "Kadoma",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "kariba-district-hospital-kariba",
    "name": "Kariba District Hospital",
    "aliases": [
      "Karoi District Hospital"
    ],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Mashonaland West",
    "district": "Kariba",
    "ward": "",
    "city": "Kariba",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "high",
    "verified": false,
    "website": ""
  },
  {
    "id": "chiredzi-district-hospital-chiredzi",
    "name": "Chiredzi District Hospital",
    "aliases": [],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Masvingo",
    "district": "Chiredzi",
    "ward": "",
    "city": "Chiredzi",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "masvingo-provincial-hospital-masvingo",
    "name": "Masvingo Provincial Hospital",
    "aliases": [],
    "facility_type": "Provincial Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Masvingo",
    "district": "Masvingo",
    "ward": "",
    "city": "Masvingo",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "morgenster-mission-hospital-masvingo",
    "name": "Morgenster Mission Hospital",
    "aliases": [],
    "facility_type": "Mission Hospital",
    "ownership": "Church",
    "rural_urban": "Urban",
    "province": "Masvingo",
    "district": "Masvingo",
    "ward": "",
    "city": "Masvingo",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "ndanga-district-hospital-ndanga",
    "name": "Ndanga District Hospital",
    "aliases": [],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Masvingo",
    "district": "Ndanga",
    "ward": "",
    "city": "Ndanga",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "hwange-colliery-hospital-hwange",
    "name": "Hwange Colliery Hospital",
    "aliases": [
      "Hwange Colliery Hospital"
    ],
    "facility_type": "District Hospital",
    "ownership": "Corporate",
    "rural_urban": "Urban",
    "province": "Matabeleland North",
    "district": "Hwange",
    "ward": "",
    "city": "Hwange",
    "address": "Railway Ave, Hwange",
    "services": [
      "ER",
      "Lab",
      "Maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "cash",
      "international medical aid",
      "local medical aid",
      "mobile money"
    ],
    "phone": "+263 281 550 11",
    "whatsapp": "+263 281 550 11",
    "email": null,
    "lat": -18.364,
    "lon": 26.501,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [
      "_",
      "a",
      "b",
      "d",
      "e",
      "g",
      "l",
      "m",
      "manual_seed",
      "n",
      "o",
      "s",
      "t",
      "u"
    ],
    "confidence": "high",
    "verified": false,
    "website": "",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "st-lukes-hospital-lupane",
    "name": "St Luke's Hospital",
    "aliases": [],
    "facility_type": "Mission Hospital",
    "ownership": "Church",
    "rural_urban": "Urban",
    "province": "Matabeleland North",
    "district": "Lupane",
    "ward": "",
    "city": "Lupane",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [
      "zach_mission_hospitals"
    ],
    "confidence": "medium",
    "verified": false,
    "website": "",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "victoria-falls-hospital-victoria-falls",
    "name": "Victoria Falls Hospital",
    "aliases": [
      "Victoria Falls Hospital"
    ],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Matabeleland North",
    "district": "Victoria Falls",
    "ward": "",
    "city": "Victoria Falls",
    "address": "Park Way, Victoria Falls",
    "services": [
      "ER",
      "Lab",
      "Maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "cash",
      "international medical aid",
      "local medical aid",
      "mobile money"
    ],
    "phone": "+263 213 2843215",
    "whatsapp": "+263 213 2843215",
    "email": null,
    "lat": -17.926,
    "lon": 25.842,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [
      "_",
      "a",
      "b",
      "d",
      "e",
      "g",
      "l",
      "m",
      "manual_seed",
      "n",
      "o",
      "s",
      "t",
      "u"
    ],
    "confidence": "high",
    "verified": false,
    "website": "",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "beitbridge-district-hospital-beitbridge",
    "name": "Beitbridge District Hospital",
    "aliases": [
      "Beitbridge District Hospital"
    ],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Matabeleland South",
    "district": "Beitbridge",
    "ward": "",
    "city": "Beitbridge",
    "address": "",
    "services": [
      "ER",
      "Inpatient",
      "Lab",
      "Maternity"
    ],
    "open_24h": false,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [
      "scribd_provincial_district_hospitals"
    ],
    "confidence": "high",
    "verified": false,
    "website": "",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "gwanda-provincial-hospital-gwanda",
    "name": "Gwanda Provincial Hospital",
    "aliases": [],
    "facility_type": "Provincial Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Matabeleland South",
    "district": "Gwanda",
    "ward": "",
    "city": "Gwanda",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "plumtree-district-hospital-plumtree",
    "name": "Plumtree District Hospital",
    "aliases": [],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Matabeleland South",
    "district": "Plumtree",
    "ward": "",
    "city": "Plumtree",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "claybank-private-hospital-gweru",
    "name": "Claybank Private Hospital",
    "aliases": [],
    "facility_type": "Private Hospital",
    "ownership": "Corporate",
    "rural_urban": "Urban",
    "province": "Midlands",
    "district": "Gweru",
    "ward": "",
    "city": "Gweru",
    "address": "",
    "services": [
      "general",
      "surgery"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "gweru-community-pharmacy-gweru",
    "name": "Gweru Community Pharmacy",
    "aliases": [
      "Gweru Community Pharmacy"
    ],
    "facility_type": "Pharmacy",
    "ownership": "Private",
    "rural_urban": "Urban",
    "province": "Midlands",
    "district": "Gweru",
    "ward": "",
    "city": "Gweru",
    "address": "",
    "services": [
      "Dispensary"
    ],
    "open_24h": true,
    "emergency_level": "Basic",
    "cost_band": null,
    "medical_aids": [],
    "phone": "+263 54 224 567",
    "whatsapp": "+263 54 224 567",
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [
      "mcaz_pharmacies_2024"
    ],
    "confidence": "high",
    "verified": true,
    "website": "",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "gweru-provincial-hospital-gweru",
    "name": "Gweru Provincial Hospital",
    "aliases": [
      "Gweru Provincial Hospital"
    ],
    "facility_type": "Provincial Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Midlands",
    "district": "Gweru",
    "ward": "",
    "city": "Gweru",
    "address": "Hospital Rd, Gweru",
    "services": [
      "ER",
      "Maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "cash",
      "international medical aid",
      "local medical aid",
      "mobile money"
    ],
    "phone": "+263-54-222-333",
    "whatsapp": "+263-54-222-333",
    "email": null,
    "lat": -19.454,
    "lon": 29.819,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "high",
    "verified": false,
    "website": "",
    "last_seen": "2025-11-20",
    "first_seen": "2025-11-20"
  },
  {
    "id": "kwekwe-general-hospital-kwekwe",
    "name": "Kwekwe General Hospital",
    "aliases": [],
    "facility_type": "Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Midlands",
    "district": "Kwekwe",
    "ward": "",
    "city": "Kwekwe",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "zvishavane-district-hospital-zvishavane",
    "name": "Zvishavane District Hospital",
    "aliases": [],
    "facility_type": "District Hospital",
    "ownership": "Government",
    "rural_urban": "Urban",
    "province": "Midlands",
    "district": "Zvishavane",
    "ward": "",
    "city": "Zvishavane",
    "address": "",
    "services": [
      "general",
      "maternity"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [
      "local medical aid",
      "international medical aid",
      "cash",
      "mobile money"
    ],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 2",
    "last_verified": "2025-11-20",
    "source": [],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "lancet-clinical-laboratories-harare",
    "name": "Lancet Clinical Laboratories Harare",
    "aliases": [
      "Lancet Labs Harare"
    ],
    "facility_type": "Lab",
    "ownership": "Private",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "",
    "services": [
      "Lab",
      "Diagnostics",
      "Pathology"
    ],
    "open_24h": false,
    "emergency_level": "",
    "cost_band": null,
    "medical_aids": [],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "",
    "source": [
      "manual_lab_entry_2025"
    ],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "lancet-clinical-laboratories-bulawayo",
    "name": "Lancet Clinical Laboratories Bulawayo",
    "aliases": [
      "Lancet Labs Bulawayo"
    ],
    "facility_type": "Lab",
    "ownership": "Private",
    "rural_urban": "Urban",
    "province": "Bulawayo",
    "district": "Bulawayo",
    "ward": "",
    "city": "Bulawayo",
    "address": "",
    "services": [
      "Lab",
      "Diagnostics",
      "Pathology"
    ],
    "open_24h": false,
    "emergency_level": "",
    "cost_band": null,
    "medical_aids": [],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "",
    "source": [
      "manual_lab_entry_2025"
    ],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "cimas-medlab-harare",
    "name": "Cimas Medlab Harare",
    "aliases": [
      "Cimas Laboratories"
    ],
    "facility_type": "Lab",
    "ownership": "Private",
    "rural_urban": "Urban",
    "province": "Harare",
    "district": "Harare",
    "ward": "",
    "city": "Harare",
    "address": "",
    "services": [
      "Lab",
      "Diagnostics",
      "Pathology"
    ],
    "open_24h": false,
    "emergency_level": "",
    "cost_band": null,
    "medical_aids": [],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "",
    "source": [
      "manual_lab_entry_2025"
    ],
    "confidence": "medium",
    "verified": false,
    "website": ""
  },
  {
    "id": "howard-mission-hospital-chiweshe",
    "name": "Howard Mission Hospital",
    "aliases": [],
    "facility_type": "Mission Hospital",
    "ownership": "Mission",
    "rural_urban": "Rural",
    "province": "Mashonaland Central",
    "district": "Chiweshe",
    "ward": "",
    "city": "Chiweshe",
    "address": "",
    "services": [
      "ER",
      "Maternity",
      "Lab",
      "Inpatient"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [
      "zach_mission_hospitals"
    ],
    "confidence": "medium",
    "verified": true,
    "website": "",
    "first_seen": "2025-11-20",
    "last_seen": "2025-11-20"
  },
  {
    "id": "st-albert-s-mission-hospital-mt-darwin",
    "name": "St Albert's Mission Hospital",
    "aliases": [],
    "facility_type": "Mission Hospital",
    "ownership": "Mission",
    "rural_urban": "Rural",
    "province": "Mashonaland Central",
    "district": "Mt Darwin",
    "ward": "",
    "city": "Mt Darwin",
    "address": "",
    "services": [
      "ER",
      "Maternity",
      "Lab",
      "Inpatient"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [
      "zach_mission_hospitals"
    ],
    "confidence": "medium",
    "verified": true,
    "website": "",
    "first_seen": "2025-11-20",
    "last_seen": "2025-11-20"
  },
  {
    "id": "all-souls-mission-hospital-mutoko",
    "name": "All Souls Mission Hospital",
    "aliases": [],
    "facility_type": "Mission Hospital",
    "ownership": "Mission",
    "rural_urban": "Rural",
    "province": "Mashonaland East",
    "district": "Mutoko",
    "ward": "",
    "city": "Mutoko",
    "address": "",
    "services": [
      "ER",
      "Maternity",
      "Lab",
      "Inpatient"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [
      "zach_mission_hospitals"
    ],
    "confidence": "medium",
    "verified": true,
    "website": "",
    "first_seen": "2025-11-20",
    "last_seen": "2025-11-20"
  },
  {
    "id": "st-theresa-s-mission-hospital-chiredzi",
    "name": "St Theresa's Mission Hospital",
    "aliases": [],
    "facility_type": "Mission Hospital",
    "ownership": "Mission",
    "rural_urban": "Rural",
    "province": "Masvingo",
    "district": "Chiredzi",
    "ward": "",
    "city": "Chiredzi",
    "address": "",
    "services": [
      "ER",
      "Maternity",
      "Lab",
      "Inpatient"
    ],
    "open_24h": true,
    "emergency_level": "Full",
    "cost_band": null,
    "medical_aids": [],
    "phone": null,
    "whatsapp": null,
    "email": null,
    "lat": null,
    "lon": null,
    "tier": "Tier 3",
    "last_verified": "2025-11-20",
    "source": [
      "zach_mission_hospitals"
    ],
    "confidence": "medium",
    "verified": true,
    "website": "",
    "first_seen": "2025-11-20",
    "last_seen": "2025-11-20"
  }
];
export default hospitalsData;
